version: '2'

services:
  redis:
    image: redis:5-alpine
    container_name: redis
    hostname: redis
    expose:
      - 6379

  tester:
    image: makeomatic/node:10.16.3-tester
    hostname: tester
    links:
      - redis
    working_dir: /src
    volumes:
      - ${PWD}:/src
    environment:
      NODE_ENV: "test"
      DEBUG: "${DEBUG}"
    command: tail -f /dev/null
